DROP DATABASE IF EXISTS petpedia;
CREATE DATABASE petpedia;

\c petpedia;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pets;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL
);

CREATE TABLE pets (
  id SERIAL PRIMARY KEY,
  owner_id INT REFERENCES users(id) ON DELETE SET NULL,
  species VARCHAR NOT NULL,
  age INT,
  name VARCHAR NOT NULL
);
